baseurl = "https://azeloc.github.io/"
languageCode = "pt-br"
title = "blog do @azeloc"
theme = "beautifulhugo"
pygmentsUseClasses = true
pygmentCodeFences = true
disqusShortname = "azeloc-github-io"
#googleAnalytics = "XXX"

[Params]
  subtitle = "um blog que é meio a minha cara"
  logo = "img/avatar-icon.jpg"
  favicon = "img/favicon.ico"
  commit = false

[Author]
  name = "Fernando Corrêa"
  email = "fcorrea@abjur.org.br"
  facebook = "fernando.filho.58"
  github = "azeloc"
  twitter = "azeloc"
  #linkedin = "username"
  #stackoverflow = "users/XXXXXXX/username"
  #soundcloud = "username"
  #instagram = "username"
  #youtube = "user/username" # or channel/channelname
  spotify = "username"
  #itchio = "username"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Sobre"
    url = "about"
    weight = 3
